export { default as Slider } from './slider/Slider';
export { default as PopularCategories } from './popularCategories/PopularCategories';
export { default as LatestRecipes } from './latestRecipes/LatestRecipes';
export { default as CurratedCollection } from './curratedCollection/CurratedCollection';
export { default as MailingList } from './mailingList/MailingList';
export { default as SuperDelicious } from './superDelicious/SuperDelicious';
export { default as ShareYourRecipe } from './shareYourRecipe/ShareYourRecipe';
export { default as CategoriesContent } from './categoriesContent/CategoriesContent';
export { default as SearchResults } from './searchResults/SearchResults';
