export enum EUrls {
  MAIN = '/',
  ABOUT = '/about/',
  CATEGORIES = '/categories',
  FAVORITES = '/favorites/',
  PROFILE = '/profile/',
  PROFILE_RECIPES = '/profile/recipes/',
  CREATE_RECIPE = '/profile/recipes/create',
  UPDATE_RECIPE = '/profile/recipes/update',
  SEARCH = '/search',
  RECIPES = '/recipes/',
  RECIPE = '/recipe',
  ADMIN_ROLES = '/admin/roles/',
  ADMIN_USERS = '/admin/users/',
  CREATE_ROLE = '/admin/roles/create/',
  UPDATE_ROLE = '/admin/roles/update/',
  MODERATOR_RECIPES = '/moderator/recipes/',
  MODERATOR_CATEGORIES = '/moderator/categories/',
  CREATE_CATEGORIE = '/moderator/categories/create',
  UPDATE_CATEGORIE = '/moderator/categories/update',
}
