export enum EUrls {
  MAIN = '/',
  ABOUT = '/about',
  CATEGORIES = '/categories',
  FAVORITES = '/favorites',
  PROFILE = '/profile',
  PROFILE_RECIPES = '/profile/recipes',
  CREATE_RECIPE = '/profile/recipes/create',
  UPDATE_RECIPE = '/profile/recipes/update',
  SEARCH = '/search',
  RECIPES = '/recipes',
  RECIPE = '/recipe',
  ADMIN = '/admin',
  CREATE_ROLE = '/admin/roles/create',
  UPDATE_ROLE = '/admin/roles/update',
  MODERATOR = '/moderator',
  CREATE_CATEGORIE = '/moderator/categories/create',
  UPDATE_CATEGORIE = '/moderator/categories/update',
}
