export { default as FacebookIcon } from './Facebook';
export { default as TwitterIcon } from './Twitter';
export { default as InstagramIcon } from './Instagram';
export type { default as IIcon } from './interface';
export { default as SearchIcon } from './Search';
export { default as LogoIcon } from './Logo';
export { default as ArrowDownIcon } from './ArrowDown';
export { default as ProfileIcon } from './Profile';
export { default as StarIcon } from './Star';
export { default as CloseIcon } from './Close';
export { default as EmailIcon } from './Email';
export { default as PasswordIcon } from './Password';
export { default as UserIcon } from './User';
export { default as LogOutIcon } from './LogOut';
export { default as PhoneIcon } from './Phone';
export { default as LikeIcon } from './Like';
export { default as ShareIcon } from './Share';
export { default as PrinterIcon } from './Printer';
